# Generated by Django 6.0.2 on 2026-02-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('ROOT', 'Root'), ('ADMIN', 'Admin'), ('DISTRIBUTOR', 'Distributor')], max_length=20),
        ),
    ]
