# Generated by Django 5.1.6 on 2026-02-13 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('NEW_USER', 'New User')], max_length=20)),
                ('priority', models.CharField(choices=[('IMPORTANT', 'Important'), ('NORMAL', 'Normal')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CLOSED', 'Closed')], db_index=True, default='PENDING', max_length=20)),
                ('availability_time', models.CharField(blank=True, max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_full_name', models.CharField(max_length=255)),
                ('customer_username', models.CharField(max_length=150)),
                ('customer_password', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_location', models.CharField(max_length=255)),
                ('vlan', models.CharField(blank=True, max_length=100, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='customers.customer')),
            ],
        ),
    ]
