# Generated by Django 6.0.2 on 2026-02-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_customer_password_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
