# Generated by Django 6.0.2 on 2026-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_username',
        ),
        migrations.AddField(
            model_name='ticket',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
