# Generated by Django 6.0.2 on 2026-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='username',
            new_name='customer_username',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='password',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='customer_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
